ENV["FASTLANE_OPT_OUT_USAGE"] = "1"
opt_out_usage

require "json"
require "fileutils"
require "shellwords"
require "xcodeproj"

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# CI env vars for release lanes:
# - ASC auth: set ASC_API_KEY_JSON or write app/fastlane/asc_api_key.json
# - Signing: MATCH_PASSWORD, MATCH_KEYCHAIN_PASSWORD, optional WWDR_CERT_PATH
APP_PROJECT = File.expand_path("../app.xcodeproj", __dir__)
APPFILE_PATH = File.expand_path("Appfile", __dir__)
APP_TARGET = "KnittingGaugeReconciler"
APP_SCHEME = "KnittingGaugeReconciler"
BUILD_OUTPUT_DIRECTORY = "."
BUILD_LOG_PATH = "../.build/gym"
CI_KEYCHAIN_NAME = "fastlane_tmp_keychain"
ASC_API_KEY_PATH = File.expand_path("asc_api_key.json", __dir__)
ASC_API_KEY_PATH_DISPLAY = "app/fastlane/asc_api_key.json"
ASC_LEGACY_ENV_VARS = %w[
  FASTLANE_USER
  FASTLANE_PASSWORD
  DELIVER_USER
  DELIVER_PASSWORD
  PILOT_USERNAME
  DELIVER_USERNAME
].freeze


def fastlane_app_identifier
  appfile_line = File.readlines(APPFILE_PATH).find { |line| line =~ /^\s*app_identifier\(/ }
  app_identifier = appfile_line&.match(/app_identifier\(["']([^"']+)["']\)/)&.captures&.first
  UI.user_error!("Unable to read app_identifier from #{APPFILE_PATH}") if app_identifier.to_s.empty?

  app_identifier
end


def release_bundle_identifier
  project = Xcodeproj::Project.open(APP_PROJECT)
  target = project.targets.find { |candidate| candidate.name == APP_TARGET }
  UI.user_error!("Unable to find Xcode target #{APP_TARGET} in #{APP_PROJECT}") unless target

  config = target.build_configurations.find { |candidate| candidate.name == "Release" } || target.build_configurations.first
  bundle_identifier = config.build_settings["PRODUCT_BUNDLE_IDENTIFIER"]
  UI.user_error!("Unable to resolve PRODUCT_BUNDLE_IDENTIFIER for #{APP_TARGET}") if bundle_identifier.to_s.empty?

  bundle_identifier
end


def release_version_number
  get_version_number(
    xcodeproj: APP_PROJECT,
    target: APP_TARGET
  )
end


def match_env_key(suffix)
  "sigh_#{fastlane_app_identifier}_appstore_#{suffix}"
end


def lane_derived_data_path(options)
  options[:derived_data_path] || ENV.fetch("DERIVED_DATA_PATH", "../.build/xcode-derived-data")
end


def lane_destination(options)
  options[:destination] || ENV["DESTINATION"] || "generic/platform=iOS Simulator"
end


def lane_test_options(options, extra_xcargs: nil)
  output_directory = options[:output_directory] || "../.build"
  result_bundle_path = File.join(output_directory, "#{APP_SCHEME}.xcresult")
  FileUtils.rm_rf(result_bundle_path)

  test_options = {
    project: APP_PROJECT,
    scheme: APP_SCHEME,
    configuration: options[:configuration] || "Debug",
    derived_data_path: lane_derived_data_path(options),
    code_coverage: true,
    result_bundle_path: result_bundle_path,
    xcargs: [
      "CODE_SIGNING_ALLOWED=NO ENABLE_TESTABILITY=YES -test-timeouts-enabled YES -default-test-execution-time-allowance 30",
      extra_xcargs,
      options[:xcargs]
    ].compact.join(" "),
    output_types: "",
    output_directory: output_directory,
    buildlog_path: output_directory,
    xcodebuild_formatter: "xcpretty"
  }

  destination = lane_destination(options)
  if options[:destination] || ENV["DESTINATION"]
    test_options[:destination] = destination
    test_options[:skip_detect_devices] = true
  else
    test_options[:devices] = [options[:device] || ENV["SIMULATOR_NAME"] || "iPhone 17 Pro"]
  end

  test_options
end


def verify_test_diagnostics(output_directory)
  result_bundle_path = File.join(output_directory, "#{APP_SCHEME}.xcresult")
  diagnostics_path = File.join(output_directory, "xcresult-diagnostics")
  raw_log_path = File.join(output_directory, "#{APP_SCHEME}-#{APP_SCHEME}.log")
  FileUtils.rm_rf(diagnostics_path)
  sh("xcrun xcresulttool export diagnostics --path #{Shellwords.escape(result_bundle_path)} --output-path #{Shellwords.escape(diagnostics_path)}")

  verifier_path = File.expand_path("diagnostics_verifier.rb", __dir__)
  sh("/usr/bin/ruby #{Shellwords.escape(verifier_path)} #{Shellwords.escape(raw_log_path)} #{Shellwords.escape(diagnostics_path)}")
end


platform :ios do
  desc "Sync certificates and provisioning profiles"
  lane :certs do
    match(type: "appstore", readonly: false)
  end

  desc "Build and test with scheme-defined scope (CI)"
  lane :ci do |options|
    swiftlint(
      mode: :lint,
      config_file: "../.swiftlint.yml",
      reporter: "xcode",
      strict: true
    )
    test_options = lane_test_options(options)
    run_tests(**test_options.merge(only_testing: ["KnittingGaugeReconcilerTests"]))
    verify_test_diagnostics(test_options[:output_directory])
  end

  desc "Build without distribution"
  lane :build do |options|
    configuration = options[:configuration] || "Debug"
    xcodebuild(
      project: APP_PROJECT,
      scheme: APP_SCHEME,
      configuration: configuration,
      sdk: options[:sdk] || "iphonesimulator",
      destination: lane_destination(options),
      build: true,
      xcargs: [
        (options[:allow_codesigning] == "true" ? nil : "CODE_SIGNING_ALLOWED=NO"),
        options[:xcargs]
      ].compact.join(" "),
      derived_data_path: lane_derived_data_path(options)
    )
  end

  private_lane :ensure_release_configuration_matches do
    configured_bundle_identifier = release_bundle_identifier
    next if configured_bundle_identifier == fastlane_app_identifier

    UI.user_error!("fastlane app_identifier=#{fastlane_app_identifier} does not match #{APP_TARGET} Release bundle ID #{configured_bundle_identifier}")
  end

  private_lane :clear_legacy_asc_auth_env do
    ASC_LEGACY_ENV_VARS.each { |key| ENV.delete(key) }
  end

  private_lane :load_asc_api_key do
    clear_legacy_asc_auth_env

    api_key_json_raw = ENV["ASC_API_KEY_JSON"]
    api_key_source = "ASC_API_KEY_JSON"

    if api_key_json_raw.to_s.empty?
      if File.exist?(ASC_API_KEY_PATH)
        api_key_json_raw = File.read(ASC_API_KEY_PATH)
        api_key_source = ASC_API_KEY_PATH_DISPLAY
      else
        UI.user_error!("Set ASC_API_KEY_JSON env var or place asc_api_key.json at #{ASC_API_KEY_PATH_DISPLAY}")
      end
    end

    begin
      api_key_json = JSON.parse(api_key_json_raw)
      app_store_connect_api_key(
        key_id: api_key_json.fetch("key_id"),
        issuer_id: api_key_json.fetch("issuer_id"),
        key_content: api_key_json.fetch("key")
      )
    rescue JSON::ParserError => error
      UI.user_error!("#{api_key_source} is not valid JSON: #{error.message}")
    rescue KeyError => error
      UI.user_error!("#{api_key_source} is missing required field: #{error.message}")
    end
  end

  private_lane :setup_ci_keychain do
    next unless ENV["CI"]

    keychain_password = ENV["MATCH_KEYCHAIN_PASSWORD"]
    UI.user_error!("Missing MATCH_KEYCHAIN_PASSWORD") if keychain_password.to_s.empty?

    create_keychain(
      name: CI_KEYCHAIN_NAME,
      password: keychain_password,
      default_keychain: true,
      add_to_search_list: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false,
      lock_after_timeout: false
    )

    existing_keychains = sh("security list-keychains -d user | xargs").strip
    sh("security list-keychains -d user -s #{Shellwords.escape("#{CI_KEYCHAIN_NAME}.keychain")} #{existing_keychains}")
  end

  private_lane :import_ci_wwdr_intermediate do
    next unless ENV["CI"]

    wwdr_cert_path = ENV["WWDR_CERT_PATH"]
    next if wwdr_cert_path.to_s.empty?

    UI.user_error!("WWDR certificate not found at #{wwdr_cert_path}") unless File.exist?(wwdr_cert_path)

    import_certificate(
      certificate_path: wwdr_cert_path,
      keychain_name: "#{CI_KEYCHAIN_NAME}.keychain",
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"]
    )
  end

  private_lane :next_testflight_build_number_for_release do |options|
    options ||= {}
    version = release_version_number
    latest_build_number = nil

    begin
      latest_build_number = latest_testflight_build_number(
        api_key: options[:api_key],
        app_identifier: fastlane_app_identifier,
        version: version,
        initial_build_number: 0
      )
    rescue StandardError => error
      raise unless error.message.to_s.match?(/Could not find a build|No build/i)
    end

    if latest_build_number.nil?
      UI.important("No TestFlight build found for version #{version}; falling back to latest build across all versions")
      latest_build_number = latest_testflight_build_number(
        api_key: options[:api_key],
        app_identifier: fastlane_app_identifier,
        initial_build_number: 0
      )
    end

    latest_build_number.to_i + 1
  end

  private_lane :appstore_signing_context do
    profile_name = ENV[match_env_key("profile-name")]
    team_id = ENV[match_env_key("team-id")]
    certificate_name = ENV[match_env_key("certificate-name")]
    provisioning_profiles = (Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING] || {}).dup
    provisioning_profiles[fastlane_app_identifier] ||= profile_name

    UI.user_error!("match did not expose a provisioning profile name for #{fastlane_app_identifier}") if profile_name.to_s.empty?
    UI.user_error!("match did not expose a development team ID for #{fastlane_app_identifier}") if team_id.to_s.empty?
    UI.user_error!("match did not expose a signing certificate name for #{fastlane_app_identifier}") if certificate_name.to_s.empty?

    {
      profile_name: profile_name,
      team_id: team_id,
      certificate_name: certificate_name,
      provisioning_profiles: provisioning_profiles
    }
  end

  private_lane :build_release_artifact do |options|
    options ||= {}
    ensure_release_configuration_matches

    if ENV["CI"]
      setup_ci_keychain
      import_ci_wwdr_intermediate
    end

    asc_api_key = load_asc_api_key
    match_options = {
      type: "appstore",
      readonly: true,
      force_for_new_devices: false,
      verbose: true,
      api_key: asc_api_key
    }
    if ENV["CI"]
      match_options[:keychain_name] = "#{CI_KEYCHAIN_NAME}.keychain"
      match_options[:keychain_password] = ENV["MATCH_KEYCHAIN_PASSWORD"]
    end

    match(**match_options)
    increment_version_number_in_xcodeproj(bump_type: options[:bump]) if options[:bump]
    increment_build_number_in_xcodeproj(
      build_number: next_testflight_build_number_for_release(api_key: asc_api_key).to_s
    )

    signing_context = appstore_signing_context
    xcargs = [
      "CODE_SIGN_STYLE=Manual",
      "DEVELOPMENT_TEAM=#{signing_context[:team_id]}",
      "PROVISIONING_PROFILE_SPECIFIER=#{Shellwords.escape(signing_context[:profile_name])}",
      "CODE_SIGN_IDENTITY=#{Shellwords.escape(signing_context[:certificate_name])}",
      "SWIFT_TREAT_WARNINGS_AS_ERRORS=YES",
      "GCC_TREAT_WARNINGS_AS_ERRORS=YES",
      "CLANG_TREAT_WARNINGS_AS_ERRORS=YES",
      "OTHER_SWIFT_FLAGS=-warnings-as-errors"
    ]
    if ENV["CI"]
      xcargs << "OTHER_CODE_SIGN_FLAGS=#{Shellwords.escape("--keychain #{CI_KEYCHAIN_NAME}.keychain")}"
    end

    build_app(
      project: APP_PROJECT,
      scheme: APP_SCHEME,
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      output_directory: BUILD_OUTPUT_DIRECTORY,
      output_name: "#{APP_TARGET}.ipa",
      archive_path: File.join(BUILD_OUTPUT_DIRECTORY, "#{APP_TARGET}.xcarchive"),
      buildlog_path: BUILD_LOG_PATH,
      derived_data_path: ENV.fetch("DERIVED_DATA_PATH", "../.build/xcode-derived-data"),
      codesigning_identity: signing_context[:certificate_name],
      skip_profile_detection: true,
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: signing_context[:provisioning_profiles]
      },
      xcargs: xcargs.join(" ")
    )

    {
      api_key: asc_api_key,
      ipa: lane_context[SharedValues::IPA_OUTPUT_PATH]
    }
  end

  desc "Build and upload to TestFlight. Optional: bump:patch|minor|major"
  lane :beta do |options|
    build_context = build_release_artifact(options)
    upload_to_testflight(
      api_key: build_context[:api_key],
      app_identifier: fastlane_app_identifier,
      ipa: build_context[:ipa],
      changelog: options[:notes],
      skip_waiting_for_build_processing: true
    )
  end

  desc "Build and submit to App Store. Optional: bump:patch|minor|major"
  lane :release do |options|
    build_context = build_release_artifact(options)
    upload_to_app_store(
      api_key: build_context[:api_key],
      app_identifier: fastlane_app_identifier,
      ipa: build_context[:ipa],
      submit_for_review: false,
      automatic_release: false,
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end
end
